spring.application.name=order-placement
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
phone-tag.payment-url=http://localhost:8082
phone-tag.fulfillment-url=http://localhost:8083
phone-tag.email-url=http://localhost:8084
phone-tag.retry-max-attempts=3
