spring.application.name=orchestrator
spring.datasource.url=jdbc:postgresql://localhost:5432/saga
spring.datasource.username=saga
spring.datasource.password=saga
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

orchestrator.order-url=http://localhost:8081
orchestrator.payment-url=http://localhost:8082
orchestrator.fulfillment-url=http://localhost:8083
orchestrator.email-url=http://localhost:8084
orchestrator.retry-max-attempts=3
